// Copyright Fury Games Pty Ltd. All rights reserved.

#pragma once

#include "CoreMinimal.h"

UENUM()
enum class EPalette : uint32
{
	Absolute_Zero = 0x0048BA UMETA(DisplayName = "Absolute Zero"),
	Acid_Green = 0xB0BF1A UMETA(DisplayName = "Acid Green"),
	Aero = 0x7CB9E8 UMETA(DisplayName = "Aero"),
	Aero_Blue = 0xC0E8D5 UMETA(DisplayName = "Aero Blue"),
	African_Violet = 0xB284BE UMETA(DisplayName = "African Violet"),
	Air_Superiority_Blue = 0x72A0C1 UMETA(DisplayName = "Air Superiority Blue"),
	Alabaster = 0xEDEAE0 UMETA(DisplayName = "Alabaster"),
	Alice_Blue = 0xF0F8FF UMETA(DisplayName = "Alice Blue"),
	Alloy_Orange = 0xC46210 UMETA(DisplayName = "Alloy Orange"),
	Almond = 0xEFDECD UMETA(DisplayName = "Almond"),
	Amaranth = 0xE52B50 UMETA(DisplayName = "Amaranth"),
	Amaranth_Pink = 0xF19CBB UMETA(DisplayName = "Amaranth Pink"),
	Amaranth_Purple = 0xAB274F UMETA(DisplayName = "Amaranth Purple"),
	Amaranth_Red = 0xD3212D UMETA(DisplayName = "Amaranth Red"),
	Amazon = 0x3B7A57 UMETA(DisplayName = "Amazon"),
	Amber = 0xFFBF00 UMETA(DisplayName = "Amber"),
	Amethyst = 0x9966CC UMETA(DisplayName = "Amethyst"),
	Android_Green = 0x3DDC84 UMETA(DisplayName = "Android Green"),
	Antique_Brass = 0xCD9575 UMETA(DisplayName = "Antique Brass"),
	Antique_Bronze = 0x665D1E UMETA(DisplayName = "Antique Bronze"),
	Antique_Fuchsia = 0x915C83 UMETA(DisplayName = "Antique Fuchsia"),
	Antique_Ruby = 0x841B2D UMETA(DisplayName = "Antique Ruby"),
	Antique_White = 0xFAEBD7 UMETA(DisplayName = "Antique White"),
	Apple_Green = 0x8DB600 UMETA(DisplayName = "Apple Green"),
	Apricot = 0xFBCEB1 UMETA(DisplayName = "Apricot"),
	Aquamarine = 0x7FFFD4 UMETA(DisplayName = "Aquamarine"),
	Arctic_Lime = 0xD0FF14 UMETA(DisplayName = "Arctic Lime"),
	Army_Green = 0x4B5320 UMETA(DisplayName = "Army Green"),
	Artichoke = 0x8F9779 UMETA(DisplayName = "Artichoke"),
	Ash_Gray = 0xB2BEB5 UMETA(DisplayName = "Ash Gray"),
	Asparagus = 0x87A96B UMETA(DisplayName = "Asparagus"),
	Atomic_Tangerine = 0xFF9966 UMETA(DisplayName = "Atomic Tangerine"),
	Auburn = 0xA52A2A UMETA(DisplayName = "Auburn"),
	Aureolin = 0xFDEE00 UMETA(DisplayName = "Aureolin"),
	Avocado = 0x568203 UMETA(DisplayName = "Avocado"),
	Azure = 0x007FFF UMETA(DisplayName = "Azure"),
	Baby_Blue = 0x89CFF0 UMETA(DisplayName = "Baby Blue"),
	Baby_Blue_Eyes = 0xA1CAF1 UMETA(DisplayName = "Baby Blue Eyes"),
	Baby_Pink = 0xF4C2C2 UMETA(DisplayName = "Baby Pink"),
	Baby_Powder = 0xFEFEFA UMETA(DisplayName = "Baby Powder"),
	Banana_Mania = 0xFAE7B5 UMETA(DisplayName = "Banana Mania"),
	Barbie_Pink = 0xDA1884 UMETA(DisplayName = "Barbie Pink"),
	Barn_Red = 0x7C0A02 UMETA(DisplayName = "Barn Red"),
	Battleship_Grey = 0x848482 UMETA(DisplayName = "Battleship Grey"),
	Beau_Blue = 0xBCD4E6 UMETA(DisplayName = "Beau Blue"),
	Beaver = 0x9F8170 UMETA(DisplayName = "Beaver"),
	Bedazzled_Blue = 0x2E5894 UMETA(DisplayName = "Bedazzled Blue"),
	Beige = 0xF5F5DC UMETA(DisplayName = "Beige"),
	Big_Dip_Ruby = 0x9C2542 UMETA(DisplayName = "Big Dip Ruby"),
	Bisque = 0xFFE4C4 UMETA(DisplayName = "Bisque"),
	Bistre = 0x3D2B1F UMETA(DisplayName = "Bistre"),
	Bitter_Lemon = 0xCAE00D UMETA(DisplayName = "Bitter Lemon"),
	Bitter_Lime = 0xBFFF00 UMETA(DisplayName = "Bitter Lime"),
	Bittersweet = 0xFE6F5E UMETA(DisplayName = "Bittersweet"),
	Bittersweet_Shimmer = 0xBF4F51 UMETA(DisplayName = "Bittersweet Shimmer"),
	Black = 0x000000 UMETA(DisplayName = "Black"),
	Black_Bean = 0x3D0C02 UMETA(DisplayName = "Black Bean"),
	Black_Chocolate = 0x1B1811 UMETA(DisplayName = "Black Chocolate"),
	Black_Coffee = 0x3B2F2F UMETA(DisplayName = "Black Coffee"),
	Black_Coral = 0x54626F UMETA(DisplayName = "Black Coral"),
	Black_Olive = 0x3B3C36 UMETA(DisplayName = "Black Olive"),
	Black_Shadows = 0xBFAFB2 UMETA(DisplayName = "Black Shadows"),
	Blanched_Almond = 0xFFEBCD UMETA(DisplayName = "Blanched Almond"),
	Blast_Off_Bronze = 0xA57164 UMETA(DisplayName = "Blast Off Bronze"),
	Bleu_De_France = 0x318CE7 UMETA(DisplayName = "Bleu De France"),
	Blizzard_Blue = 0xACE5EE UMETA(DisplayName = "Blizzard Blue"),
	Blond = 0xFAF0BE UMETA(DisplayName = "Blond"),
	Blood_Red = 0x660000 UMETA(DisplayName = "Blood Red"),
	Blue = 0x0000FF UMETA(DisplayName = "Blue"),
	Blue_Bell = 0xA2A2D0 UMETA(DisplayName = "Blue Bell"),
	Blue_Gray = 0x6699CC UMETA(DisplayName = "Blue Gray"),
	Blue_Green = 0x0D98BA UMETA(DisplayName = "Blue Green"),
	Blue_Jeans = 0x5DADEC UMETA(DisplayName = "Blue Jeans"),
	Blue_Munsell = 0x0093AF UMETA(DisplayName = "Blue Munsell"),
	Blue_Ncs = 0x0087BD UMETA(DisplayName = "Blue Ncs"),
	Blue_Pantone = 0x0018A8 UMETA(DisplayName = "Blue Pantone"),
	Blue_Pigment = 0x333399 UMETA(DisplayName = "Blue Pigment"),
	Blue_Ryb = 0x0247FE UMETA(DisplayName = "Blue Ryb"),
	Blue_Sapphire = 0x126180 UMETA(DisplayName = "Blue Sapphire"),
	Blue_Violet = 0x8A2BE2 UMETA(DisplayName = "Blue Violet"),
	Blue_Yonder = 0x5072A7 UMETA(DisplayName = "Blue Yonder"),
	Bluetiful = 0x3C69E7 UMETA(DisplayName = "Bluetiful"),
	Blush = 0xDE5D83 UMETA(DisplayName = "Blush"),
	Bole = 0x79443B UMETA(DisplayName = "Bole"),
	Bone = 0xE3DAC9 UMETA(DisplayName = "Bone"),
	Bottle_Green = 0x006A4E UMETA(DisplayName = "Bottle Green"),
	Brandy = 0x87413F UMETA(DisplayName = "Brandy"),
	Brick_Red = 0xCB4154 UMETA(DisplayName = "Brick Red"),
	Bright_Green = 0x66FF00 UMETA(DisplayName = "Bright Green"),
	Bright_Lilac = 0xD891EF UMETA(DisplayName = "Bright Lilac"),
	Bright_Navy_Blue = 0x1974D2 UMETA(DisplayName = "Bright Navy Blue"),
	Brilliant_Rose = 0xFF55A3 UMETA(DisplayName = "Brilliant Rose"),
	Brink_Pink = 0xFB607F UMETA(DisplayName = "Brink Pink"),
	British_Racing_Green = 0x004225 UMETA(DisplayName = "British Racing Green"),
	Bronze = 0xCD7F32 UMETA(DisplayName = "Bronze"),
	Brown = 0x88540B UMETA(DisplayName = "Brown"),
	Brown_Sugar = 0xAF6E4D UMETA(DisplayName = "Brown Sugar"),
	Bud_Green = 0x7BB661 UMETA(DisplayName = "Bud Green"),
	Buff = 0xFFC680 UMETA(DisplayName = "Buff"),
	Burgundy = 0x800020 UMETA(DisplayName = "Burgundy"),
	Burlywood = 0xDEB887 UMETA(DisplayName = "Burlywood"),
	Burnished_Brown = 0xA17A74 UMETA(DisplayName = "Burnished Brown"),
	Burnt_Orange = 0xCC5500 UMETA(DisplayName = "Burnt Orange"),
	Burnt_Sienna = 0xE97451 UMETA(DisplayName = "Burnt Sienna"),
	Burnt_Umber = 0x8A3324 UMETA(DisplayName = "Burnt Umber"),
	Byzantine = 0xBD33A4 UMETA(DisplayName = "Byzantine"),
	Byzantium = 0x702963 UMETA(DisplayName = "Byzantium"),
	Cadet = 0x536872 UMETA(DisplayName = "Cadet"),
	Cadet_Blue = 0x5F9EA0 UMETA(DisplayName = "Cadet Blue"),
	Cadet_Grey = 0x91A3B0 UMETA(DisplayName = "Cadet Grey"),
	Cadmium_Green = 0x006B3C UMETA(DisplayName = "Cadmium Green"),
	Cadmium_Orange = 0xED872D UMETA(DisplayName = "Cadmium Orange"),
	Cadmium_Red = 0xE30022 UMETA(DisplayName = "Cadmium Red"),
	Cadmium_Yellow = 0xFFF600 UMETA(DisplayName = "Cadmium Yellow"),
	Cafe_Noir = 0x4B3621 UMETA(DisplayName = "Cafe Noir"),
	Cambridge_Blue = 0xA3C1AD UMETA(DisplayName = "Cambridge Blue"),
	Cameo_Pink = 0xEFBBCC UMETA(DisplayName = "Cameo Pink"),
	Canary = 0xFFFF99 UMETA(DisplayName = "Canary"),
	Canary_Yellow = 0xFFEF00 UMETA(DisplayName = "Canary Yellow"),
	Candy_Apple_Red = 0xFF0800 UMETA(DisplayName = "Candy Apple Red"),
	Candy_Pink = 0xE4717A UMETA(DisplayName = "Candy Pink"),
	Capri = 0x00BFFF UMETA(DisplayName = "Capri"),
	Caput_Mortuum = 0x592720 UMETA(DisplayName = "Caput Mortuum"),
	Cardinal = 0xC41E3A UMETA(DisplayName = "Cardinal"),
	Caribbean_Green = 0x00CC99 UMETA(DisplayName = "Caribbean Green"),
	Carmine = 0x960018 UMETA(DisplayName = "Carmine"),
	Carmine_Mp = 0xD70040 UMETA(DisplayName = "Carmine Mp"),
	Carnation_Pink = 0xFFA6C9 UMETA(DisplayName = "Carnation Pink"),
	Carolina_Blue = 0x56A0D3 UMETA(DisplayName = "Carolina Blue"),
	Carrot_Orange = 0xED9121 UMETA(DisplayName = "Carrot Orange"),
	Castleton_Green = 0x00563F UMETA(DisplayName = "Castleton Green"),
	Catawba = 0x703642 UMETA(DisplayName = "Catawba"),
	Cedar_Chest = 0xC95A49 UMETA(DisplayName = "Cedar Chest"),
	Celadon = 0xACE1AF UMETA(DisplayName = "Celadon"),
	Celadon_Green = 0x2F847C UMETA(DisplayName = "Celadon Green"),
	Celeste_Blue = 0xB2FFFF UMETA(DisplayName = "Celeste Blue"),
	Celtic_Blue = 0x246BCE UMETA(DisplayName = "Celtic Blue"),
	Cerise = 0xDE3163 UMETA(DisplayName = "Cerise"),
	Cerulean = 0x007BA7 UMETA(DisplayName = "Cerulean"),
	Cerulean_Blue = 0x2A52BE UMETA(DisplayName = "Cerulean Blue"),
	Cerulean_Frost = 0x6D9BC3 UMETA(DisplayName = "Cerulean Frost"),
	Cg_Blue = 0x007AA5 UMETA(DisplayName = "Cg Blue"),
	Cg_Red = 0xE03C31 UMETA(DisplayName = "Cg Red"),
	Champagne = 0xF7E7CE UMETA(DisplayName = "Champagne"),
	Champagne_Pink = 0xF1DDCF UMETA(DisplayName = "Champagne Pink"),
	Charcoal = 0x36454F UMETA(DisplayName = "Charcoal"),
	Charleston_Green = 0x232B2B UMETA(DisplayName = "Charleston Green"),
	Charm_Pink = 0xE68FAC UMETA(DisplayName = "Charm Pink"),
	Cherry_Blossom_Pink = 0xFFB7C5 UMETA(DisplayName = "Cherry Blossom Pink"),
	Chestnut = 0x954535 UMETA(DisplayName = "Chestnut"),
	Chili_Red = 0xE23D28 UMETA(DisplayName = "Chili Red"),
	China_Pink = 0xDE6FA1 UMETA(DisplayName = "China Pink"),
	China_Rose = 0xA8516E UMETA(DisplayName = "China Rose"),
	Chinese_Red = 0xAA381E UMETA(DisplayName = "Chinese Red"),
	Chinese_Violet = 0x856088 UMETA(DisplayName = "Chinese Violet"),
	Chinese_Yellow = 0xFFB200 UMETA(DisplayName = "Chinese Yellow"),
	Chocolate_Cosmos = 0x58111A UMETA(DisplayName = "Chocolate Cosmos"),
	Chrome_Yellow = 0xFFA700 UMETA(DisplayName = "Chrome Yellow"),
	Cinereous = 0x98817B UMETA(DisplayName = "Cinereous"),
	Cinnamon_Satin = 0xCD607E UMETA(DisplayName = "Cinnamon Satin"),
	Citrine = 0xE4D00A UMETA(DisplayName = "Citrine"),
	Citron = 0x9FA91F UMETA(DisplayName = "Citron"),
	Claret = 0x7F1734 UMETA(DisplayName = "Claret"),
	Cobalt_Blue = 0x0047AB UMETA(DisplayName = "Cobalt Blue"),
	Coffee = 0x6F4E37 UMETA(DisplayName = "Coffee"),
	Colorwheel_Blue_Green = 0x064E40 UMETA(DisplayName = "Colorwheel Blue Green"),
	Colorwheel_Blue_Violet =
		0x4D1A7F UMETA(DisplayName = "Colorwheel Blue Violet"),
	Colorwheel_Red_Orange = 0xFF4500 UMETA(DisplayName = "Colorwheel Red Orange"),
	Colorwheel_Red_Violet = 0x922B3E UMETA(DisplayName = "Colorwheel Red Violet"),
	Colorwheel_Violet = 0x7F00FF UMETA(DisplayName = "Colorwheel Violet"),
	Colorwheel_Yellow_Green =
		0x30B21A UMETA(DisplayName = "Colorwheel Yellow Green"),
	Colorwheel_Yellow_Orange =
		0xFF9505 UMETA(DisplayName = "Colorwheel Yellow Orange"),
	Columbia_Blue = 0xB9D9EB UMETA(DisplayName = "Columbia Blue"),
	Computer_Dark_Green = 0x006400 UMETA(DisplayName = "Computer Dark Green"),
	Computer_Gray = 0xBEBEBE UMETA(DisplayName = "Computer Gray"),
	Computer_Khaki_Light = 0xF0E68C UMETA(DisplayName = "Computer Khaki Light"),
	Computer_Maroon = 0xB03060 UMETA(DisplayName = "Computer Maroon"),
	Cool_Grey = 0x8C92AC UMETA(DisplayName = "Cool Grey"),
	Copper = 0xB87333 UMETA(DisplayName = "Copper"),
	Copper_Penny = 0xAD6F69 UMETA(DisplayName = "Copper Penny"),
	Copper_Red = 0xCB6D51 UMETA(DisplayName = "Copper Red"),
	Copper_Rose = 0x996666 UMETA(DisplayName = "Copper Rose"),
	Coquelicot = 0xFF3800 UMETA(DisplayName = "Coquelicot"),
	Coral = 0xFF7F50 UMETA(DisplayName = "Coral"),
	Coral_Pink = 0xF88379 UMETA(DisplayName = "Coral Pink"),
	Cordovan = 0x893F45 UMETA(DisplayName = "Cordovan"),
	Corn = 0xFBEC5D UMETA(DisplayName = "Corn"),
	Cornell_Red = 0xB31B1B UMETA(DisplayName = "Cornell Red"),
	Cornflower_Blue = 0x6495ED UMETA(DisplayName = "Cornflower Blue"),
	Cornsilk = 0xFFF8DC UMETA(DisplayName = "Cornsilk"),
	Cosmic_Cobalt = 0x2E2D88 UMETA(DisplayName = "Cosmic Cobalt"),
	Cosmic_Latte = 0xFFF8E7 UMETA(DisplayName = "Cosmic Latte"),
	Cotton_Candy = 0xFFBCD9 UMETA(DisplayName = "Cotton Candy"),
	Coyote_Brown = 0x81613C UMETA(DisplayName = "Coyote Brown"),
	Crayon_Blue = 0x1F75FE UMETA(DisplayName = "Crayon Blue"),
	Crayon_Blue_Violet = 0x7366BD UMETA(DisplayName = "Crayon Blue Violet"),
	Crayon_Bright_Yellow = 0xFFAA1D UMETA(DisplayName = "Crayon Bright Yellow"),
	Crayon_Cadet_Blue = 0xA9B2C3 UMETA(DisplayName = "Crayon Cadet Blue"),
	Crayon_Cerulean = 0x1DACD6 UMETA(DisplayName = "Crayon Cerulean"),
	Crayon_Copper = 0xDA8A67 UMETA(DisplayName = "Crayon Copper"),
	Crayon_Forest_Green = 0x5FA777 UMETA(DisplayName = "Crayon Forest Green"),
	Crayon_Fuchsia = 0xC154C1 UMETA(DisplayName = "Crayon Fuchsia"),
	Crayon_Gold = 0xE6BE8A UMETA(DisplayName = "Crayon Gold"),
	Crayon_Green = 0x1CAC78 UMETA(DisplayName = "Crayon Green"),
	Crayon_Green_Blue = 0x2887C8 UMETA(DisplayName = "Crayon Green Blue"),
	Crayon_Green_Yellow = 0xF0E891 UMETA(DisplayName = "Crayon Green Yellow"),
	Crayon_Lemon_Yellow = 0xFFFF9F UMETA(DisplayName = "Crayon Lemon Yellow"),
	Crayon_Magenta = 0xF653A6 UMETA(DisplayName = "Crayon Magenta"),
	Crayon_Maize = 0xF2C649 UMETA(DisplayName = "Crayon Maize"),
	Crayon_Maroon = 0xC32148 UMETA(DisplayName = "Crayon Maroon"),
	Crayon_Mulberry = 0xC8509B UMETA(DisplayName = "Crayon Mulberry"),
	Crayon_Orange = 0xFF7538 UMETA(DisplayName = "Crayon Orange"),
	Crayon_Orange_Red = 0xFF5349 UMETA(DisplayName = "Crayon Orange Red"),
	Crayon_Orange_Yellow = 0xF8D568 UMETA(DisplayName = "Crayon Orange Yellow"),
	Crayon_Orchid = 0xE29CD2 UMETA(DisplayName = "Crayon Orchid"),
	Crayon_Outer_Space = 0x2D383A UMETA(DisplayName = "Crayon Outer Space"),
	Crayon_Peach = 0xFFCBA4 UMETA(DisplayName = "Crayon Peach"),
	Crayon_Periwinkle = 0xC3CDE6 UMETA(DisplayName = "Crayon Periwinkle"),
	Crayon_Red = 0xEE204D UMETA(DisplayName = "Crayon Red"),
	Crayon_Red_Violet = 0xC0448F UMETA(DisplayName = "Crayon Red Violet"),
	Crayon_Sapphire = 0x2D5DA1 UMETA(DisplayName = "Crayon Sapphire"),
	Crayon_Sea_Green = 0x00FFCD UMETA(DisplayName = "Crayon Sea Green"),
	Crayon_Silver = 0xC9C0BB UMETA(DisplayName = "Crayon Silver"),
	Crayon_Sky_Blue = 0x76D7EA UMETA(DisplayName = "Crayon Sky Blue"),
	Crayon_Spring_Green = 0xECEBBD UMETA(DisplayName = "Crayon Spring Green"),
	Crayon_Tan = 0xD99A6C UMETA(DisplayName = "Crayon Tan"),
	Crayon_Violet = 0x963D7F UMETA(DisplayName = "Crayon Violet"),
	Crayon_Violet_Blue = 0x766EC8 UMETA(DisplayName = "Crayon Violet Blue"),
	Crayon_Yellow = 0xFCE883 UMETA(DisplayName = "Crayon Yellow"),
	Crayon_Yellow_Green = 0xC5E384 UMETA(DisplayName = "Crayon Yellow Green"),
	Cream = 0xFFFDD0 UMETA(DisplayName = "Cream"),
	Crimson = 0xDC143C UMETA(DisplayName = "Crimson"),
	Crimson_Ua = 0x9E1B32 UMETA(DisplayName = "Crimson Ua"),
	Crystal = 0xA7D8DE UMETA(DisplayName = "Crystal"),
	Cultured = 0xF5F5F5 UMETA(DisplayName = "Cultured"),
	Cyan = 0x00FFFF UMETA(DisplayName = "Cyan"),
	Cyan_Process = 0x00B7EB UMETA(DisplayName = "Cyan Process"),
	Cyber_Grape = 0x58427C UMETA(DisplayName = "Cyber Grape"),
	Cyber_Yellow = 0xFFD300 UMETA(DisplayName = "Cyber Yellow"),
	Cyclamen = 0xF56FA1 UMETA(DisplayName = "Cyclamen"),
	Dark_Blue_Gray = 0x666699 UMETA(DisplayName = "Dark Blue Gray"),
	Dark_Brown = 0x654321 UMETA(DisplayName = "Dark Brown"),
	Dark_Byzantium = 0x5D3954 UMETA(DisplayName = "Dark Byzantium"),
	Dark_Cornflower_Blue = 0x26428B UMETA(DisplayName = "Dark Cornflower Blue"),
	Dark_Cyan = 0x008B8B UMETA(DisplayName = "Dark Cyan"),
	Dark_Electric_Blue = 0x536878 UMETA(DisplayName = "Dark Electric Blue"),
	Dark_Goldenrod = 0xB8860B UMETA(DisplayName = "Dark Goldenrod"),
	Dark_Green = 0x013220 UMETA(DisplayName = "Dark Green"),
	Dark_Jungle_Green = 0x1A2421 UMETA(DisplayName = "Dark Jungle Green"),
	Dark_Khaki = 0xBDB76B UMETA(DisplayName = "Dark Khaki"),
	Dark_Lava = 0x483C32 UMETA(DisplayName = "Dark Lava"),
	Dark_Liver = 0x534B4F UMETA(DisplayName = "Dark Liver"),
	Dark_Liver_Horses = 0x543D37 UMETA(DisplayName = "Dark Liver Horses"),
	Dark_Magenta = 0x8B008B UMETA(DisplayName = "Dark Magenta"),
	Dark_Moss_Green = 0x4A5D23 UMETA(DisplayName = "Dark Moss Green"),
	Dark_Olive_Green = 0x556B2F UMETA(DisplayName = "Dark Olive Green"),
	Dark_Orange = 0xFF8C00 UMETA(DisplayName = "Dark Orange"),
	Dark_Orchid = 0x9932CC UMETA(DisplayName = "Dark Orchid"),
	Dark_Pastel_Green = 0x03C03C UMETA(DisplayName = "Dark Pastel Green"),
	Dark_Purple = 0x301934 UMETA(DisplayName = "Dark Purple"),
	Dark_Red = 0x8B0000 UMETA(DisplayName = "Dark Red"),
	Dark_Salmon = 0xE9967A UMETA(DisplayName = "Dark Salmon"),
	Dark_Sea_Green = 0x8FBC8F UMETA(DisplayName = "Dark Sea Green"),
	Dark_Sienna = 0x3C1414 UMETA(DisplayName = "Dark Sienna"),
	Dark_Sky_Blue = 0x8CBED6 UMETA(DisplayName = "Dark Sky Blue"),
	Dark_Slate_Blue = 0x483D8B UMETA(DisplayName = "Dark Slate Blue"),
	Dark_Slate_Gray = 0x2F4F4F UMETA(DisplayName = "Dark Slate Gray"),
	Dark_Spring_Green = 0x177245 UMETA(DisplayName = "Dark Spring Green"),
	Dark_Turquoise = 0x00CED1 UMETA(DisplayName = "Dark Turquoise"),
	Dark_Violet = 0x9400D3 UMETA(DisplayName = "Dark Violet"),
	Dartmouth_Green = 0x00703C UMETA(DisplayName = "Dartmouth Green"),
	Davys_Grey = 0x555555 UMETA(DisplayName = "Davys Grey"),
	Deep_Cerise = 0xDA3287 UMETA(DisplayName = "Deep Cerise"),
	Deep_Chestnut = 0xB94E48 UMETA(DisplayName = "Deep Chestnut"),
	Deep_Jungle_Green = 0x004B49 UMETA(DisplayName = "Deep Jungle Green"),
	Deep_Pink = 0xFF1493 UMETA(DisplayName = "Deep Pink"),
	Deep_Saffron = 0xFF9933 UMETA(DisplayName = "Deep Saffron"),
	Deep_Space_Sparkle = 0x4A646C UMETA(DisplayName = "Deep Space Sparkle"),
	Deep_Taupe = 0x7E5E60 UMETA(DisplayName = "Deep Taupe"),
	Denim = 0x1560BD UMETA(DisplayName = "Denim"),
	Denim_Blue = 0x2243B6 UMETA(DisplayName = "Denim Blue"),
	Desert_Sand = 0xEDC9AF UMETA(DisplayName = "Desert Sand"),
	Dim_Gray = 0x696969 UMETA(DisplayName = "Dim Gray"),
	Dodger_Blue = 0x1E90FF UMETA(DisplayName = "Dodger Blue"),
	Dogwood_Rose = 0xD71868 UMETA(DisplayName = "Dogwood Rose"),
	Duke_Blue = 0x00009C UMETA(DisplayName = "Duke Blue"),
	Dutch_White = 0xEFDFBB UMETA(DisplayName = "Dutch White"),
	Earth_Yellow = 0xE1A95F UMETA(DisplayName = "Earth Yellow"),
	Ebony = 0x555D50 UMETA(DisplayName = "Ebony"),
	Eerie_Black = 0x1B1B1B UMETA(DisplayName = "Eerie Black"),
	Eggplant = 0x614051 UMETA(DisplayName = "Eggplant"),
	Eggshell = 0xF0EAD6 UMETA(DisplayName = "Eggshell"),
	Egyptian_Blue = 0x1034A6 UMETA(DisplayName = "Egyptian Blue"),
	Eigengrau = 0x16161D UMETA(DisplayName = "Eigengrau"),
	Electric_Blue = 0x7DF9FF UMETA(DisplayName = "Electric Blue"),
	Electric_Indigo = 0x6F00FF UMETA(DisplayName = "Electric Indigo"),
	Electric_Lime = 0xCCFF00 UMETA(DisplayName = "Electric Lime"),
	Electric_Purple = 0xBF00FF UMETA(DisplayName = "Electric Purple"),
	Emerald = 0x50C878 UMETA(DisplayName = "Emerald"),
	Eminence = 0x6C3082 UMETA(DisplayName = "Eminence"),
	English_Green = 0x1B4D3E UMETA(DisplayName = "English Green"),
	English_Lavender = 0xB48395 UMETA(DisplayName = "English Lavender"),
	English_Red = 0xAB4B52 UMETA(DisplayName = "English Red"),
	English_Vermillion = 0xCC474B UMETA(DisplayName = "English Vermillion"),
	English_Violet = 0x563C5C UMETA(DisplayName = "English Violet"),
	Erin = 0x00FF40 UMETA(DisplayName = "Erin"),
	Eton_Blue = 0x96C8A2 UMETA(DisplayName = "Eton Blue"),
	Falu_Red = 0x801818 UMETA(DisplayName = "Falu Red"),
	Fandango = 0xB53389 UMETA(DisplayName = "Fandango"),
	Fandango_Pink = 0xDE5285 UMETA(DisplayName = "Fandango Pink"),
	Fashion_Fuchsia = 0xF400A1 UMETA(DisplayName = "Fashion Fuchsia"),
	Fawn = 0xE5AA70 UMETA(DisplayName = "Fawn"),
	Feldgrau = 0x4D5D53 UMETA(DisplayName = "Feldgrau"),
	Fern_Green = 0x4F7942 UMETA(DisplayName = "Fern Green"),
	Field_Drab = 0x6C541E UMETA(DisplayName = "Field Drab"),
	Fiery_Rose = 0xFF5470 UMETA(DisplayName = "Fiery Rose"),
	Fire_Engine_Red = 0xCE2029 UMETA(DisplayName = "Fire Engine Red"),
	Fire_Opal = 0xE95C4B UMETA(DisplayName = "Fire Opal"),
	Firebrick = 0xB22222 UMETA(DisplayName = "Firebrick"),
	Flame = 0xE25822 UMETA(DisplayName = "Flame"),
	Flax = 0xEEDC82 UMETA(DisplayName = "Flax"),
	Flirt = 0xA2006D UMETA(DisplayName = "Flirt"),
	Floral_White = 0xFFFAF0 UMETA(DisplayName = "Floral White"),
	Fluorescent_Blue = 0x15F4EE UMETA(DisplayName = "Fluorescent Blue"),
	French_Beige = 0xA67B5B UMETA(DisplayName = "French Beige"),
	French_Bistre = 0x856D4D UMETA(DisplayName = "French Bistre"),
	French_Blue = 0x0072BB UMETA(DisplayName = "French Blue"),
	French_Fuchsia = 0xFD3F92 UMETA(DisplayName = "French Fuchsia"),
	French_Lilac = 0x86608E UMETA(DisplayName = "French Lilac"),
	French_Lime = 0x9EFD38 UMETA(DisplayName = "French Lime"),
	French_Mauve = 0xD473D4 UMETA(DisplayName = "French Mauve"),
	French_Pink = 0xFD6C9E UMETA(DisplayName = "French Pink"),
	French_Raspberry = 0xC72C48 UMETA(DisplayName = "French Raspberry"),
	French_Rose = 0xF64A8A UMETA(DisplayName = "French Rose"),
	French_Sky_Blue = 0x77B5FE UMETA(DisplayName = "French Sky Blue"),
	French_Violet = 0x8806CE UMETA(DisplayName = "French Violet"),
	Frostbite = 0xE936A7 UMETA(DisplayName = "Frostbite"),
	Fuchsia_Purple = 0xCC397B UMETA(DisplayName = "Fuchsia Purple"),
	Fuchsia_Rose = 0xC74375 UMETA(DisplayName = "Fuchsia Rose"),
	Fulvous = 0xE48400 UMETA(DisplayName = "Fulvous"),
	Fuzzy_Wuzzy = 0x87421F UMETA(DisplayName = "Fuzzy Wuzzy"),
	Gainsboro = 0xDCDCDC UMETA(DisplayName = "Gainsboro"),
	Gamboge = 0xE49B0F UMETA(DisplayName = "Gamboge"),
	Generic_Viridian = 0x007F66 UMETA(DisplayName = "Generic Viridian"),
	Ghost_White = 0xF8F8FF UMETA(DisplayName = "Ghost White"),
	Glaucous = 0x6082B6 UMETA(DisplayName = "Glaucous"),
	Glossy_Grape = 0xAB92B3 UMETA(DisplayName = "Glossy Grape"),
	Go_Green = 0x00AB66 UMETA(DisplayName = "Go Green"),
	Gold = 0xA57C00 UMETA(DisplayName = "Gold"),
	Gold_Fusion = 0x85754E UMETA(DisplayName = "Gold Fusion"),
	Gold_Metallic = 0xD4AF37 UMETA(DisplayName = "Gold Metallic"),
	Golden_Brown = 0x996515 UMETA(DisplayName = "Golden Brown"),
	Golden_Poppy = 0xFCC200 UMETA(DisplayName = "Golden Poppy"),
	Golden_Yellow = 0xFFDF00 UMETA(DisplayName = "Golden Yellow"),
	Goldenrod = 0xDAA520 UMETA(DisplayName = "Goldenrod"),
	Gotham_Green = 0x00573F UMETA(DisplayName = "Gotham Green"),
	Granite_Gray = 0x676767 UMETA(DisplayName = "Granite Gray"),
	Granny_Smith_Apple = 0xA8E4A0 UMETA(DisplayName = "Granny Smith Apple"),
	Green = 0x00FF00 UMETA(DisplayName = "Green"),
	Green_Blue = 0x1164B4 UMETA(DisplayName = "Green Blue"),
	Green_Cyan = 0x009966 UMETA(DisplayName = "Green Cyan"),
	Green_Lizard = 0xA7F432 UMETA(DisplayName = "Green Lizard"),
	Green_Munsell = 0x00A877 UMETA(DisplayName = "Green Munsell"),
	Green_Ncs = 0x009F6B UMETA(DisplayName = "Green Ncs"),
	Green_Pantone = 0x00AD43 UMETA(DisplayName = "Green Pantone"),
	Green_Pigment = 0x00A550 UMETA(DisplayName = "Green Pigment"),
	Green_Ryb = 0x66B032 UMETA(DisplayName = "Green Ryb"),
	Green_Sheen = 0x6EAEA1 UMETA(DisplayName = "Green Sheen"),
	Green_Yellow = 0xADFF2F UMETA(DisplayName = "Green Yellow"),
	Grullo = 0xA99A86 UMETA(DisplayName = "Grullo"),
	Gunmetal = 0x2a3439 UMETA(DisplayName = "Gunmetal"),
	Han_Blue = 0x446CCF UMETA(DisplayName = "Han Blue"),
	Han_Purple = 0x5218FA UMETA(DisplayName = "Han Purple"),
	Hansa_Yellow = 0xE9D66B UMETA(DisplayName = "Hansa Yellow"),
	Harlequin = 0x3FFF00 UMETA(DisplayName = "Harlequin"),
	Harvest_Gold = 0xDA9100 UMETA(DisplayName = "Harvest Gold"),
	Heat_Wave = 0xFF7A00 UMETA(DisplayName = "Heat Wave"),
	Heliotrope = 0xDF73FF UMETA(DisplayName = "Heliotrope"),
	Honeydew = 0xF0FFF0 UMETA(DisplayName = "Honeydew"),
	Honolulu_Blue = 0x006DB0 UMETA(DisplayName = "Honolulu Blue"),
	Hookers_Green = 0x49796B UMETA(DisplayName = "Hookers Green"),
	Hot_Magenta = 0xFF1DCE UMETA(DisplayName = "Hot Magenta"),
	Hot_Pink = 0xFF69B4 UMETA(DisplayName = "Hot Pink"),
	Hunter_Green = 0x355E3B UMETA(DisplayName = "Hunter Green"),
	Iceberg = 0x71A6D2 UMETA(DisplayName = "Iceberg"),
	Icterine = 0xFCF75E UMETA(DisplayName = "Icterine"),
	Illuminating_Emerald = 0x319177 UMETA(DisplayName = "Illuminating Emerald"),
	Imperial_Red = 0xED2939 UMETA(DisplayName = "Imperial Red"),
	Inchworm = 0xB2EC5D UMETA(DisplayName = "Inchworm"),
	Independence = 0x4C516D UMETA(DisplayName = "Independence"),
	India_Green = 0x138808 UMETA(DisplayName = "India Green"),
	Indian_Red = 0xCD5C5C UMETA(DisplayName = "Indian Red"),
	Indian_Yellow = 0xE3A857 UMETA(DisplayName = "Indian Yellow"),
	Indigo = 0x4B0082 UMETA(DisplayName = "Indigo"),
	Indigo_Dye = 0x00416A UMETA(DisplayName = "Indigo Dye"),
	Infrared = 0xFF496C UMETA(DisplayName = "Infrared"),
	International_Klein_Blue =
		0x130a8f UMETA(DisplayName = "International Klein Blue"),
	International_Orange_Aerospace =
		0xFF4F00 UMETA(DisplayName = "International Orange Aerospace"),
	International_Orange_Engineering =
		0xBA160C UMETA(DisplayName = "International Orange Engineering"),
	International_Orange_Golden_Gate_Bridge =
		0xC0362C UMETA(DisplayName = "International Orange Golden Gate Bridge"),
	Iris = 0x5A4FCF UMETA(DisplayName = "Iris"),
	Isabelline = 0xF4F0EC UMETA(DisplayName = "Isabelline"),
	Ivory = 0xFFFFF0 UMETA(DisplayName = "Ivory"),
	Jade = 0x00A86B UMETA(DisplayName = "Jade"),
	Japanese_Carmine = 0x9D2933 UMETA(DisplayName = "Japanese Carmine"),
	Japanese_Violet = 0x5B3256 UMETA(DisplayName = "Japanese Violet"),
	Jasmine = 0xF8DE7E UMETA(DisplayName = "Jasmine"),
	Jazzberry_Jam = 0xA50B5E UMETA(DisplayName = "Jazzberry Jam"),
	Jet = 0x343434 UMETA(DisplayName = "Jet"),
	Jonquil = 0xF4CA16 UMETA(DisplayName = "Jonquil"),
	June_Bud = 0xBDDA57 UMETA(DisplayName = "June Bud"),
	Jungle_Green = 0x29AB87 UMETA(DisplayName = "Jungle Green"),
	Kelly_Green = 0x4CBB17 UMETA(DisplayName = "Kelly Green"),
	Keppel = 0x3AB09E UMETA(DisplayName = "Keppel"),
	Key_Lime = 0xE8F48C UMETA(DisplayName = "Key Lime"),
	Kobi = 0xE79FC4 UMETA(DisplayName = "Kobi"),
	Kobicha = 0x6B4423 UMETA(DisplayName = "Kobicha"),
	Kombu_Green = 0x354230 UMETA(DisplayName = "Kombu Green"),
	Ksu_Purple = 0x512888 UMETA(DisplayName = "Ksu Purple"),
	Languid_Lavender = 0xD6CADD UMETA(DisplayName = "Languid Lavender"),
	Lapis_Lazuli = 0x26619C UMETA(DisplayName = "Lapis Lazuli"),
	Laser_Lemon = 0xFFFF66 UMETA(DisplayName = "Laser Lemon"),
	Laurel_Green = 0xA9BA9D UMETA(DisplayName = "Laurel Green"),
	Lava = 0xCF1020 UMETA(DisplayName = "Lava"),
	Lavender_Blue = 0xCCCCFF UMETA(DisplayName = "Lavender Blue"),
	Lavender_Blush = 0xFFF0F5 UMETA(DisplayName = "Lavender Blush"),
	Lavender_Floral = 0xB57EDC UMETA(DisplayName = "Lavender Floral"),
	Lavender_Gray = 0xC4C3D0 UMETA(DisplayName = "Lavender Gray"),
	Lawn_Green = 0x7CFC00 UMETA(DisplayName = "Lawn Green"),
	Lemon = 0xFFF700 UMETA(DisplayName = "Lemon"),
	Lemon_Chiffon = 0xFFFACD UMETA(DisplayName = "Lemon Chiffon"),
	Lemon_Curry = 0xCCA01D UMETA(DisplayName = "Lemon Curry"),
	Lemon_Glacier = 0xFDFF00 UMETA(DisplayName = "Lemon Glacier"),
	Lemon_Meringue = 0xF6EABE UMETA(DisplayName = "Lemon Meringue"),
	Lemon_Yellow = 0xFFF44F UMETA(DisplayName = "Lemon Yellow"),
	Liberty = 0x545AA7 UMETA(DisplayName = "Liberty"),
	Light_Blue = 0xADD8E6 UMETA(DisplayName = "Light Blue"),
	Light_Coral = 0xF08080 UMETA(DisplayName = "Light Coral"),
	Light_Cornflower_Blue = 0x93CCEA UMETA(DisplayName = "Light Cornflower Blue"),
	Light_Cyan = 0xE0FFFF UMETA(DisplayName = "Light Cyan"),
	Light_French_Beige = 0xC8AD7F UMETA(DisplayName = "Light French Beige"),
	Light_Goldenrod_Yellow =
		0xFAFAD2 UMETA(DisplayName = "Light Goldenrod Yellow"),
	Light_Gray = 0xD3D3D3 UMETA(DisplayName = "Light Gray"),
	Light_Green = 0x90EE90 UMETA(DisplayName = "Light Green"),
	Light_Orange = 0xFED8B1 UMETA(DisplayName = "Light Orange"),
	Light_Periwinkle = 0xC5CBE1 UMETA(DisplayName = "Light Periwinkle"),
	Light_Pink = 0xFFB6C1 UMETA(DisplayName = "Light Pink"),
	Light_Salmon = 0xFFA07A UMETA(DisplayName = "Light Salmon"),
	Light_Sea_Green = 0x20B2AA UMETA(DisplayName = "Light Sea Green"),
	Light_Sky_Blue = 0x87CEFA UMETA(DisplayName = "Light Sky Blue"),
	Light_Slate_Gray = 0x778899 UMETA(DisplayName = "Light Slate Gray"),
	Light_Steel_Blue = 0xB0C4DE UMETA(DisplayName = "Light Steel Blue"),
	Light_Yellow = 0xFFFFE0 UMETA(DisplayName = "Light Yellow"),
	Lilac = 0xC8A2C8 UMETA(DisplayName = "Lilac"),
	Lilac_Luster = 0xAE98AA UMETA(DisplayName = "Lilac Luster"),
	Lime_Green = 0x32CD32 UMETA(DisplayName = "Lime Green"),
	Lincoln_Green = 0x195905 UMETA(DisplayName = "Lincoln Green"),
	Linen = 0xFAF0E6 UMETA(DisplayName = "Linen"),
	Little_Boy_Blue = 0x6CA0DC UMETA(DisplayName = "Little Boy Blue"),
	Liver = 0x674C47 UMETA(DisplayName = "Liver"),
	Liver_Chestnut = 0x987456 UMETA(DisplayName = "Liver Chestnut"),
	Liver_Dogs = 0xB86D29 UMETA(DisplayName = "Liver Dogs"),
	Liver_Organ = 0x6C2E1F UMETA(DisplayName = "Liver Organ"),
	Macaroni_And_Cheese = 0xFFBD88 UMETA(DisplayName = "Macaroni And Cheese"),
	Madder_Lake = 0xCC3336 UMETA(DisplayName = "Madder Lake"),
	Magenta = 0xFF00FF UMETA(DisplayName = "Magenta"),
	Magenta_Dye = 0xCA1F7B UMETA(DisplayName = "Magenta Dye"),
	Magenta_Haze = 0x9F4576 UMETA(DisplayName = "Magenta Haze"),
	Magenta_Pantone = 0xD0417E UMETA(DisplayName = "Magenta Pantone"),
	Magenta_Process = 0xFF0090 UMETA(DisplayName = "Magenta Process"),
	Magic_Mint = 0xAAF0D1 UMETA(DisplayName = "Magic Mint"),
	Magnolia = 0xF2E8D7 UMETA(DisplayName = "Magnolia"),
	Mahogany = 0xC04000 UMETA(DisplayName = "Mahogany"),
	Majorelle_Blue = 0x6050DC UMETA(DisplayName = "Majorelle Blue"),
	Malachite = 0x0BDA51 UMETA(DisplayName = "Malachite"),
	Manatee = 0x979AAA UMETA(DisplayName = "Manatee"),
	Mandarin = 0xF37A48 UMETA(DisplayName = "Mandarin"),
	Mango = 0xFDBE02 UMETA(DisplayName = "Mango"),
	Mango_Tango = 0xFF8243 UMETA(DisplayName = "Mango Tango"),
	Mantis = 0x74C365 UMETA(DisplayName = "Mantis"),
	Mardi_Gras = 0x880085 UMETA(DisplayName = "Mardi Gras"),
	Marigold = 0xEAA221 UMETA(DisplayName = "Marigold"),
	Mauve = 0xE0B0FF UMETA(DisplayName = "Mauve"),
	Mauvelous = 0xEF98AA UMETA(DisplayName = "Mauvelous"),
	Maximum_Blue = 0x47ABCC UMETA(DisplayName = "Maximum Blue"),
	Maximum_Blue_Green = 0x30BFBF UMETA(DisplayName = "Maximum Blue Green"),
	Maximum_Blue_Purple = 0xACACE6 UMETA(DisplayName = "Maximum Blue Purple"),
	Maximum_Green = 0x5E8C31 UMETA(DisplayName = "Maximum Green"),
	Maximum_Green_Yellow = 0xD9E650 UMETA(DisplayName = "Maximum Green Yellow"),
	Maximum_Purple = 0x733380 UMETA(DisplayName = "Maximum Purple"),
	Maximum_Red = 0xD92121 UMETA(DisplayName = "Maximum Red"),
	Maximum_Red_Purple = 0xA63A79 UMETA(DisplayName = "Maximum Red Purple"),
	Maximum_Yellow = 0xFAFA37 UMETA(DisplayName = "Maximum Yellow"),
	Maximum_Yellow_Red = 0xF2BA49 UMETA(DisplayName = "Maximum Yellow Red"),
	May_Green = 0x4C9141 UMETA(DisplayName = "May Green"),
	Maya_Blue = 0x73C2FB UMETA(DisplayName = "Maya Blue"),
	Medium_Aquamarine = 0x66DDAA UMETA(DisplayName = "Medium Aquamarine"),
	Medium_Blue = 0x0000CD UMETA(DisplayName = "Medium Blue"),
	Medium_Candy_Apple_Red =
		0xE2062C UMETA(DisplayName = "Medium Candy Apple Red"),
	Medium_Carmine = 0xAF4035 UMETA(DisplayName = "Medium Carmine"),
	Medium_Orchid = 0xBA55D3 UMETA(DisplayName = "Medium Orchid"),
	Medium_Purple = 0x9370DB UMETA(DisplayName = "Medium Purple"),
	Medium_Sea_Green = 0x3CB371 UMETA(DisplayName = "Medium Sea Green"),
	Medium_Slate_Blue = 0x7B68EE UMETA(DisplayName = "Medium Slate Blue"),
	Medium_Spring_Green = 0x00FA9A UMETA(DisplayName = "Medium Spring Green"),
	Medium_Turquoise = 0x48D1CC UMETA(DisplayName = "Medium Turquoise"),
	Mellow_Apricot = 0xF8B878 UMETA(DisplayName = "Mellow Apricot"),
	Melon = 0xFEBAAD UMETA(DisplayName = "Melon"),
	Metallic_Gold = 0xD3AF37 UMETA(DisplayName = "Metallic Gold"),
	Metallic_Seaweed = 0x0A7E8C UMETA(DisplayName = "Metallic Seaweed"),
	Metallic_Sunburst = 0x9C7C38 UMETA(DisplayName = "Metallic Sunburst"),
	Mexican_Pink = 0xE4007C UMETA(DisplayName = "Mexican Pink"),
	Middle_Blue = 0x7ED4E6 UMETA(DisplayName = "Middle Blue"),
	Middle_Blue_Green = 0x8DD9CC UMETA(DisplayName = "Middle Blue Green"),
	Middle_Blue_Purple = 0x8B72BE UMETA(DisplayName = "Middle Blue Purple"),
	Middle_Green = 0x4D8C57 UMETA(DisplayName = "Middle Green"),
	Middle_Green_Yellow = 0xACBF60 UMETA(DisplayName = "Middle Green Yellow"),
	Middle_Grey = 0x8B8680 UMETA(DisplayName = "Middle Grey"),
	Middle_Purple = 0xD982B5 UMETA(DisplayName = "Middle Purple"),
	Middle_Red = 0xE58E73 UMETA(DisplayName = "Middle Red"),
	Middle_Red_Purple = 0xA55353 UMETA(DisplayName = "Middle Red Purple"),
	Middle_Yellow = 0xFFEB00 UMETA(DisplayName = "Middle Yellow"),
	Middle_Yellow_Red = 0xECB176 UMETA(DisplayName = "Middle Yellow Red"),
	Midnight = 0x702670 UMETA(DisplayName = "Midnight"),
	Midnight_Blue = 0x191970 UMETA(DisplayName = "Midnight Blue"),
	Midnight_Green_Eagle = 0x004953 UMETA(DisplayName = "Midnight Green Eagle"),
	Mikado_Yellow = 0xFFC40C UMETA(DisplayName = "Mikado Yellow"),
	Mimi_Pink = 0xFFDAE9 UMETA(DisplayName = "Mimi Pink"),
	Mindaro = 0xE3F988 UMETA(DisplayName = "Mindaro"),
	Ming = 0x36747D UMETA(DisplayName = "Ming"),
	Minion_Yellow = 0xF5E050 UMETA(DisplayName = "Minion Yellow"),
	Mint = 0x3EB489 UMETA(DisplayName = "Mint"),
	Mint_Cream = 0xF5FFFA UMETA(DisplayName = "Mint Cream"),
	Mint_Green = 0x98FF98 UMETA(DisplayName = "Mint Green"),
	Misty_Moss = 0xBBB477 UMETA(DisplayName = "Misty Moss"),
	Misty_Rose = 0xFFE4E1 UMETA(DisplayName = "Misty Rose"),
	Morning_Blue = 0x8DA399 UMETA(DisplayName = "Morning Blue"),
	Moss_Green = 0x8A9A5B UMETA(DisplayName = "Moss Green"),
	Mountain_Meadow = 0x30BA8F UMETA(DisplayName = "Mountain Meadow"),
	Mountbatten_Pink = 0x997A8D UMETA(DisplayName = "Mountbatten Pink"),
	Msu_Green = 0x18453B UMETA(DisplayName = "Msu Green"),
	Mulberry = 0xC54B8C UMETA(DisplayName = "Mulberry"),
	Mustard = 0xFFDB58 UMETA(DisplayName = "Mustard"),
	Myrtle_Green = 0x317873 UMETA(DisplayName = "Myrtle Green"),
	Mystic = 0xD65282 UMETA(DisplayName = "Mystic"),
	Mystic_Maroon = 0xAD4379 UMETA(DisplayName = "Mystic Maroon"),
	Nadeshiko_Pink = 0xF6ADC6 UMETA(DisplayName = "Nadeshiko Pink"),
	Navajo_White = 0xFFDEAD UMETA(DisplayName = "Navajo White"),
	Navy_Blue = 0x000080 UMETA(DisplayName = "Navy Blue"),
	Neon_Blue = 0x4666FF UMETA(DisplayName = "Neon Blue"),
	Neon_Carrot = 0xFFA343 UMETA(DisplayName = "Neon Carrot"),
	Neon_Fuchsia = 0xFE4164 UMETA(DisplayName = "Neon Fuchsia"),
	Neon_Green = 0x39FF14 UMETA(DisplayName = "Neon Green"),
	New_York_Pink = 0xD7837F UMETA(DisplayName = "New York Pink"),
	Nickel = 0x727472 UMETA(DisplayName = "Nickel"),
	Non_Photo_Blue = 0xA4DDED UMETA(DisplayName = "Non Photo Blue"),
	Nyanza = 0xE9FFDB UMETA(DisplayName = "Nyanza"),
	Ocean_Blue = 0x4F42B5 UMETA(DisplayName = "Ocean Blue"),
	Ocean_Green = 0x48BF91 UMETA(DisplayName = "Ocean Green"),
	Ochre = 0xCC7722 UMETA(DisplayName = "Ochre"),
	Old_Burgundy = 0x43302E UMETA(DisplayName = "Old Burgundy"),
	Old_Gold = 0xCFB53B UMETA(DisplayName = "Old Gold"),
	Old_Lace = 0xFDF5E6 UMETA(DisplayName = "Old Lace"),
	Old_Lavender = 0x796878 UMETA(DisplayName = "Old Lavender"),
	Old_Mauve = 0x673147 UMETA(DisplayName = "Old Mauve"),
	Old_Rose = 0xC08081 UMETA(DisplayName = "Old Rose"),
	Olive = 0x808000 UMETA(DisplayName = "Olive"),
	Olive_Drab_3 = 0x6B8E23 UMETA(DisplayName = "Olive Drab 3"),
	Olive_Drab_7 = 0x3C341F UMETA(DisplayName = "Olive Drab 7"),
	Olive_Green = 0xB5B35C UMETA(DisplayName = "Olive Green"),
	Olivine = 0x9AB973 UMETA(DisplayName = "Olivine"),
	Onyx = 0x353839 UMETA(DisplayName = "Onyx"),
	Opal = 0xA8C3BC UMETA(DisplayName = "Opal"),
	Opera_Mauve = 0xB784A7 UMETA(DisplayName = "Opera Mauve"),
	Orange = 0xFF7F00 UMETA(DisplayName = "Orange"),
	Orange_Pantone = 0xFF5800 UMETA(DisplayName = "Orange Pantone"),
	Orange_Peel = 0xFF9F00 UMETA(DisplayName = "Orange Peel"),
	Orange_Soda = 0xFA5B3D UMETA(DisplayName = "Orange Soda"),
	Orange_Yellow = 0xF5BD1F UMETA(DisplayName = "Orange Yellow"),
	Orchid = 0xDA70D6 UMETA(DisplayName = "Orchid"),
	Orchid_Pink = 0xF2BDCD UMETA(DisplayName = "Orchid Pink"),
	Ou_Crimson_Red = 0x841617 UMETA(DisplayName = "Ou Crimson Red"),
	Outrageous_Orange = 0xFF6E4A UMETA(DisplayName = "Outrageous Orange"),
	Oxblood = 0x4A0000 UMETA(DisplayName = "Oxblood"),
	Oxford_Blue = 0x002147 UMETA(DisplayName = "Oxford Blue"),
	Pacific_Blue = 0x1CA9C9 UMETA(DisplayName = "Pacific Blue"),
	Pakistan_Green = 0x006600 UMETA(DisplayName = "Pakistan Green"),
	Palatinate_Purple = 0x682860 UMETA(DisplayName = "Palatinate Purple"),
	Pale_Cerulean = 0x9BC4E2 UMETA(DisplayName = "Pale Cerulean"),
	Pale_Pink = 0xFADADD UMETA(DisplayName = "Pale Pink"),
	Pale_Purple_Pantone = 0xFAE6FA UMETA(DisplayName = "Pale Purple Pantone"),
	Pansy_Purple = 0x78184A UMETA(DisplayName = "Pansy Purple"),
	Paolo_Veronese_Green = 0x009B7D UMETA(DisplayName = "Paolo Veronese Green"),
	Papaya_Whip = 0xFFEFD5 UMETA(DisplayName = "Papaya Whip"),
	Paradise_Pink = 0xE63E62 UMETA(DisplayName = "Paradise Pink"),
	Parchment = 0xF1E9D2 UMETA(DisplayName = "Parchment"),
	Pastel_Pink = 0xDEA5A4 UMETA(DisplayName = "Pastel Pink"),
	Peach = 0xFFE5B4 UMETA(DisplayName = "Peach"),
	Peach_Puff = 0xFFDAB9 UMETA(DisplayName = "Peach Puff"),
	Pear = 0xD1E231 UMETA(DisplayName = "Pear"),
	Pearly_Purple = 0xB768A2 UMETA(DisplayName = "Pearly Purple"),
	Permanent_Geranium_Lake =
		0xE12C2C UMETA(DisplayName = "Permanent Geranium Lake"),
	Persian_Blue = 0x1C39BB UMETA(DisplayName = "Persian Blue"),
	Persian_Green = 0x00A693 UMETA(DisplayName = "Persian Green"),
	Persian_Indigo = 0x32127A UMETA(DisplayName = "Persian Indigo"),
	Persian_Orange = 0xD99058 UMETA(DisplayName = "Persian Orange"),
	Persian_Pink = 0xF77FBE UMETA(DisplayName = "Persian Pink"),
	Persian_Red = 0xCC3333 UMETA(DisplayName = "Persian Red"),
	Persian_Rose = 0xFE28A2 UMETA(DisplayName = "Persian Rose"),
	Persimmon = 0xEC5800 UMETA(DisplayName = "Persimmon"),
	Pewter_Blue = 0x8BA8B7 UMETA(DisplayName = "Pewter Blue"),
	Phthalo_Blue = 0x000F89 UMETA(DisplayName = "Phthalo Blue"),
	Phthalo_Green = 0x123524 UMETA(DisplayName = "Phthalo Green"),
	Picotee_Blue = 0x2E2787 UMETA(DisplayName = "Picotee Blue"),
	Pictorial_Carmine = 0xC30B4E UMETA(DisplayName = "Pictorial Carmine"),
	Piggy_Pink = 0xFDDDE6 UMETA(DisplayName = "Piggy Pink"),
	Pine_Green = 0x01796F UMETA(DisplayName = "Pine Green"),
	Pine_Tree = 0x2A2F23 UMETA(DisplayName = "Pine Tree"),
	Pink = 0xFFC0CB UMETA(DisplayName = "Pink"),
	Pink_Flamingo = 0xFC74FD UMETA(DisplayName = "Pink Flamingo"),
	Pink_Lace = 0xFFDDF4 UMETA(DisplayName = "Pink Lace"),
	Pink_Lavender = 0xD8B2D1 UMETA(DisplayName = "Pink Lavender"),
	Pink_Pantone = 0xD74894 UMETA(DisplayName = "Pink Pantone"),
	Pink_Sherbet = 0xF78FA7 UMETA(DisplayName = "Pink Sherbet"),
	Pistachio = 0x93C572 UMETA(DisplayName = "Pistachio"),
	Platinum = 0xE5E4E2 UMETA(DisplayName = "Platinum"),
	Plum = 0x8E4585 UMETA(DisplayName = "Plum"),
	Plump_Purple = 0x5946B2 UMETA(DisplayName = "Plump Purple"),
	Polished_Pine = 0x5DA493 UMETA(DisplayName = "Polished Pine"),
	Popstar = 0xBE4F62 UMETA(DisplayName = "Popstar"),
	Portland_Orange = 0xFF5A36 UMETA(DisplayName = "Portland Orange"),
	Powder_Blue = 0xB0E0E6 UMETA(DisplayName = "Powder Blue"),
	Princeton_Orange = 0xF58025 UMETA(DisplayName = "Princeton Orange"),
	Prune = 0x701C1C UMETA(DisplayName = "Prune"),
	Prussian_Blue = 0x003153 UMETA(DisplayName = "Prussian Blue"),
	Psychedelic_Purple = 0xDF00FF UMETA(DisplayName = "Psychedelic Purple"),
	Puce = 0xCC8899 UMETA(DisplayName = "Puce"),
	Pullman_Brown_Ups = 0x644117 UMETA(DisplayName = "Pullman Brown Ups"),
	Pumpkin = 0xFF7518 UMETA(DisplayName = "Pumpkin"),
	Purple = 0x6A0DAD UMETA(DisplayName = "Purple"),
	Purple_Mountain_Majesty =
		0x9678B6 UMETA(DisplayName = "Purple Mountain Majesty"),
	Purple_Munsell = 0x9F00C5 UMETA(DisplayName = "Purple Munsell"),
	Purple_Navy = 0x4E5180 UMETA(DisplayName = "Purple Navy"),
	Purple_Pizzazz = 0xFE4EDA UMETA(DisplayName = "Purple Pizzazz"),
	Purple_Plum = 0x9C51B6 UMETA(DisplayName = "Purple Plum"),
	Purpureus = 0x9A4EAE UMETA(DisplayName = "Purpureus"),
	Queen_Blue = 0x436B95 UMETA(DisplayName = "Queen Blue"),
	Queen_Pink = 0xE8CCD7 UMETA(DisplayName = "Queen Pink"),
	Quick_Silver = 0xA6A6A6 UMETA(DisplayName = "Quick Silver"),
	Quinacridone_Magenta = 0x8E3A59 UMETA(DisplayName = "Quinacridone Magenta"),
	Radical_Red = 0xFF355E UMETA(DisplayName = "Radical Red"),
	Raisin_Black = 0x242124 UMETA(DisplayName = "Raisin Black"),
	Rajah = 0xFBAB60 UMETA(DisplayName = "Rajah"),
	Raspberry = 0xE30B5D UMETA(DisplayName = "Raspberry"),
	Raspberry_Glace = 0x915F6D UMETA(DisplayName = "Raspberry Glace"),
	Raspberry_Rose = 0xB3446C UMETA(DisplayName = "Raspberry Rose"),
	Raw_Sienna = 0xD68A59 UMETA(DisplayName = "Raw Sienna"),
	Raw_Umber = 0x826644 UMETA(DisplayName = "Raw Umber"),
	Razzle_Dazzle_Rose = 0xFF33CC UMETA(DisplayName = "Razzle Dazzle Rose"),
	Razzmatazz = 0xE3256B UMETA(DisplayName = "Razzmatazz"),
	Razzmic_Berry = 0x8D4E85 UMETA(DisplayName = "Razzmic Berry"),
	Rebecca_Purple = 0x663399 UMETA(DisplayName = "Rebecca Purple"),
	Red = 0xFF0000 UMETA(DisplayName = "Red"),
	Red_Munsell = 0xF2003C UMETA(DisplayName = "Red Munsell"),
	Red_Ncs = 0xC40233 UMETA(DisplayName = "Red Ncs"),
	Red_Pigment = 0xED1C24 UMETA(DisplayName = "Red Pigment"),
	Red_Purple = 0xE40078 UMETA(DisplayName = "Red Purple"),
	Red_Ryb = 0xFE2712 UMETA(DisplayName = "Red Ryb"),
	Red_Salsa = 0xFD3A4A UMETA(DisplayName = "Red Salsa"),
	Red_Violet = 0xC71585 UMETA(DisplayName = "Red Violet"),
	Redwood = 0xA45A52 UMETA(DisplayName = "Redwood"),
	Resolution_Blue = 0x002387 UMETA(DisplayName = "Resolution Blue"),
	Rhythm = 0x777696 UMETA(DisplayName = "Rhythm"),
	Rich_Black = 0x004040 UMETA(DisplayName = "Rich Black"),
	Rich_Black_Fogra29 = 0x010B13 UMETA(DisplayName = "Rich Black Fogra29"),
	Rich_Black_Fogra39 = 0x010203 UMETA(DisplayName = "Rich Black Fogra39"),
	Rifle_Green = 0x444C38 UMETA(DisplayName = "Rifle Green"),
	Robin_Egg_Blue = 0x00CCCC UMETA(DisplayName = "Robin Egg Blue"),
	Rocket_Metallic = 0x8A7F80 UMETA(DisplayName = "Rocket Metallic"),
	Rojo_Spanish_Red = 0xA91101 UMETA(DisplayName = "Rojo Spanish Red"),
	Roman_Silver = 0x838996 UMETA(DisplayName = "Roman Silver"),
	Rose = 0xFF007F UMETA(DisplayName = "Rose"),
	Rose_Bonbon = 0xF9429E UMETA(DisplayName = "Rose Bonbon"),
	Rose_Dust = 0x9E5E6F UMETA(DisplayName = "Rose Dust"),
	Rose_Ebony = 0x674846 UMETA(DisplayName = "Rose Ebony"),
	Rose_Madder = 0xE32636 UMETA(DisplayName = "Rose Madder"),
	Rose_Pink = 0xFF66CC UMETA(DisplayName = "Rose Pink"),
	Rose_Pompadour = 0xED7A9B UMETA(DisplayName = "Rose Pompadour"),
	Rose_Quartz = 0xAA98A9 UMETA(DisplayName = "Rose Quartz"),
	Rose_Red = 0xC21E56 UMETA(DisplayName = "Rose Red"),
	Rose_Taupe = 0x905D5D UMETA(DisplayName = "Rose Taupe"),
	Rose_Vale = 0xAB4E52 UMETA(DisplayName = "Rose Vale"),
	Rosewood = 0x65000B UMETA(DisplayName = "Rosewood"),
	Rosso_Corsa = 0xD40000 UMETA(DisplayName = "Rosso Corsa"),
	Rosy_Brown = 0xBC8F8F UMETA(DisplayName = "Rosy Brown"),
	Royal_Blue_Dark = 0x002366 UMETA(DisplayName = "Royal Blue Dark"),
	Royal_Blue_Light = 0x4169E1 UMETA(DisplayName = "Royal Blue Light"),
	Royal_Purple = 0x7851A9 UMETA(DisplayName = "Royal Purple"),
	Royal_Yellow = 0xFADA5E UMETA(DisplayName = "Royal Yellow"),
	Ruber = 0xCE4676 UMETA(DisplayName = "Ruber"),
	Rubine_Red = 0xD10056 UMETA(DisplayName = "Rubine Red"),
	Ruby = 0xE0115F UMETA(DisplayName = "Ruby"),
	Ruby_Red = 0x9B111E UMETA(DisplayName = "Ruby Red"),
	Rufous = 0xA81C07 UMETA(DisplayName = "Rufous"),
	Russet = 0x80461B UMETA(DisplayName = "Russet"),
	Russian_Green = 0x679267 UMETA(DisplayName = "Russian Green"),
	Russian_Violet = 0x32174D UMETA(DisplayName = "Russian Violet"),
	Rust = 0xB7410E UMETA(DisplayName = "Rust"),
	Rusty_Red = 0xDA2C43 UMETA(DisplayName = "Rusty Red"),
	Sacramento_State_Green =
		0x043927 UMETA(DisplayName = "Sacramento State Green"),
	Saddle_Brown = 0x8B4513 UMETA(DisplayName = "Saddle Brown"),
	Safety_Orange = 0xFF7800 UMETA(DisplayName = "Safety Orange"),
	Safety_Orange_Blaze = 0xFF6700 UMETA(DisplayName = "Safety Orange Blaze"),
	Safety_Yellow = 0xEED202 UMETA(DisplayName = "Safety Yellow"),
	Saffron = 0xF4C430 UMETA(DisplayName = "Saffron"),
	Sage = 0xBCB88A UMETA(DisplayName = "Sage"),
	Salmon = 0xFA8072 UMETA(DisplayName = "Salmon"),
	Salmon_Pink = 0xFF91A4 UMETA(DisplayName = "Salmon Pink"),
	Sand = 0xC2B280 UMETA(DisplayName = "Sand"),
	Sand_Dune = 0x967117 UMETA(DisplayName = "Sand Dune"),
	Sandy_Brown = 0xF4A460 UMETA(DisplayName = "Sandy Brown"),
	Sap_Green = 0x507D2A UMETA(DisplayName = "Sap Green"),
	Sapphire = 0x0F52BA UMETA(DisplayName = "Sapphire"),
	Sapphire_Blue = 0x0067A5 UMETA(DisplayName = "Sapphire Blue"),
	Satin_Sheen_Gold = 0xCBA135 UMETA(DisplayName = "Satin Sheen Gold"),
	Scarlet = 0xFF2400 UMETA(DisplayName = "Scarlet"),
	Schauss_Pink = 0xFF91AF UMETA(DisplayName = "Schauss Pink"),
	School_Bus_Yellow = 0xFFD800 UMETA(DisplayName = "School Bus Yellow"),
	Screamin_Green = 0x66FF66 UMETA(DisplayName = "Screamin Green"),
	Sea_Green = 0x2E8B57 UMETA(DisplayName = "Sea Green"),
	Seal_Brown = 0x59260B UMETA(DisplayName = "Seal Brown"),
	Seashell = 0xFFF5EE UMETA(DisplayName = "Seashell"),
	Selective_Yellow = 0xFFBA00 UMETA(DisplayName = "Selective Yellow"),
	Sepia = 0x704214 UMETA(DisplayName = "Sepia"),
	Shadow = 0x8A795D UMETA(DisplayName = "Shadow"),
	Shadow_Blue = 0x778BA5 UMETA(DisplayName = "Shadow Blue"),
	Shamrock_Green = 0x009E60 UMETA(DisplayName = "Shamrock Green"),
	Sheen_Green = 0x8FD400 UMETA(DisplayName = "Sheen Green"),
	Shimmering_Blush = 0xD98695 UMETA(DisplayName = "Shimmering Blush"),
	Shiny_Shamrock = 0x5FA778 UMETA(DisplayName = "Shiny Shamrock"),
	Shocking_Pink = 0xFC0FC0 UMETA(DisplayName = "Shocking Pink"),
	Sienna = 0x882D17 UMETA(DisplayName = "Sienna"),
	Silver = 0xC0C0C0 UMETA(DisplayName = "Silver"),
	Silver_Chalice = 0xACACAC UMETA(DisplayName = "Silver Chalice"),
	Silver_Metallic = 0xAAA9AD UMETA(DisplayName = "Silver Metallic"),
	Silver_Pink = 0xC4AEAD UMETA(DisplayName = "Silver Pink"),
	Silver_Sand = 0xBFC1C2 UMETA(DisplayName = "Silver Sand"),
	Sinopia = 0xCB410B UMETA(DisplayName = "Sinopia"),
	Sizzling_Red = 0xFF3855 UMETA(DisplayName = "Sizzling Red"),
	Sizzling_Sunrise = 0xFFDB00 UMETA(DisplayName = "Sizzling Sunrise"),
	Skobeloff = 0x007474 UMETA(DisplayName = "Skobeloff"),
	Sky_Blue = 0x87CEEB UMETA(DisplayName = "Sky Blue"),
	Sky_Magenta = 0xCF71AF UMETA(DisplayName = "Sky Magenta"),
	Slate_Blue = 0x6A5ACD UMETA(DisplayName = "Slate Blue"),
	Slate_Gray = 0x708090 UMETA(DisplayName = "Slate Gray"),
	Slimy_Green = 0x299617 UMETA(DisplayName = "Slimy Green"),
	Smitten = 0xC84186 UMETA(DisplayName = "Smitten"),
	Smoky_Black = 0x100C08 UMETA(DisplayName = "Smoky Black"),
	Snow = 0xFFFAFA UMETA(DisplayName = "Snow"),
	Solid_Pink = 0x893843 UMETA(DisplayName = "Solid Pink"),
	Sonic_Silver = 0x757575 UMETA(DisplayName = "Sonic Silver"),
	Space_Cadet = 0x1D2951 UMETA(DisplayName = "Space Cadet"),
	Spanish_Bistre = 0x807532 UMETA(DisplayName = "Spanish Bistre"),
	Spanish_Blue = 0x0070B8 UMETA(DisplayName = "Spanish Blue"),
	Spanish_Carmine = 0xD10047 UMETA(DisplayName = "Spanish Carmine"),
	Spanish_Gray = 0x989898 UMETA(DisplayName = "Spanish Gray"),
	Spanish_Green = 0x009150 UMETA(DisplayName = "Spanish Green"),
	Spanish_Orange = 0xE86100 UMETA(DisplayName = "Spanish Orange"),
	Spanish_Pink = 0xF7BFBE UMETA(DisplayName = "Spanish Pink"),
	Spanish_Red = 0xE60026 UMETA(DisplayName = "Spanish Red"),
	Spanish_Violet = 0x4C2882 UMETA(DisplayName = "Spanish Violet"),
	Spanish_Viridian = 0x007F5C UMETA(DisplayName = "Spanish Viridian"),
	Spring_Bud = 0xA7FC00 UMETA(DisplayName = "Spring Bud"),
	Spring_Frost = 0x87FF2A UMETA(DisplayName = "Spring Frost"),
	Spring_Green = 0x00FF7F UMETA(DisplayName = "Spring Green"),
	St_Patricks_Blue = 0x23297A UMETA(DisplayName = "St Patricks Blue"),
	Star_Command_Blue = 0x007BB8 UMETA(DisplayName = "Star Command Blue"),
	Steel_Blue = 0x4682B4 UMETA(DisplayName = "Steel Blue"),
	Steel_Pink = 0xCC33CC UMETA(DisplayName = "Steel Pink"),
	Steel_Teal = 0x5F8A8B UMETA(DisplayName = "Steel Teal"),
	Straw = 0xE4D96F UMETA(DisplayName = "Straw"),
	Strawberry = 0xFA5053 UMETA(DisplayName = "Strawberry"),
	Strawberry_Blonde = 0xFF9361 UMETA(DisplayName = "Strawberry Blonde"),
	Sugar_Plum = 0x914E75 UMETA(DisplayName = "Sugar Plum"),
	Sunglow = 0xFFCC33 UMETA(DisplayName = "Sunglow"),
	Sunray = 0xE3AB57 UMETA(DisplayName = "Sunray"),
	Sunset = 0xFAD6A5 UMETA(DisplayName = "Sunset"),
	Super_Pink = 0xCF6BA9 UMETA(DisplayName = "Super Pink"),
	Sweet_Brown = 0xA83731 UMETA(DisplayName = "Sweet Brown"),
	Syracuse_Orange = 0xD44500 UMETA(DisplayName = "Syracuse Orange"),
	Tan = 0xD2B48C UMETA(DisplayName = "Tan"),
	Tangerine = 0xF28500 UMETA(DisplayName = "Tangerine"),
	Tart_Orange = 0xFB4D46 UMETA(DisplayName = "Tart Orange"),
	Taupe_Gray = 0x8B8589 UMETA(DisplayName = "Taupe Gray"),
	Tea_Green = 0xD0F0C0 UMETA(DisplayName = "Tea Green"),
	Teal = 0x008080 UMETA(DisplayName = "Teal"),
	Teal_Blue = 0x367588 UMETA(DisplayName = "Teal Blue"),
	Telemagenta = 0xCF3476 UMETA(DisplayName = "Telemagenta"),
	Tenne = 0xCD5700 UMETA(DisplayName = "Tenne"),
	Terra_Cotta = 0xE2725B UMETA(DisplayName = "Terra Cotta"),
	Thistle = 0xD8BFD8 UMETA(DisplayName = "Thistle"),
	Tickle_Me_Pink = 0xFC89AC UMETA(DisplayName = "Tickle Me Pink"),
	Tiffany_Blue = 0x0ABAB5 UMETA(DisplayName = "Tiffany Blue"),
	Timberwolf = 0xDBD7D2 UMETA(DisplayName = "Timberwolf"),
	Titanium_Yellow = 0xEEE600 UMETA(DisplayName = "Titanium Yellow"),
	Tomato = 0xFF6347 UMETA(DisplayName = "Tomato"),
	Traditional_Chartreuse =
		0xDFFF00 UMETA(DisplayName = "Traditional Chartreuse"),
	Traditional_Chocolate = 0x7B3F00 UMETA(DisplayName = "Traditional Chocolate"),
	Traditional_Forest_Green =
		0x014421 UMETA(DisplayName = "Traditional Forest Green"),
	Tropical_Rainforest = 0x00755E UMETA(DisplayName = "Tropical Rainforest"),
	True_Blue = 0x2D68C4 UMETA(DisplayName = "True Blue"),
	Trypan_Blue = 0x1C05B3 UMETA(DisplayName = "Trypan Blue"),
	Tufts_Blue = 0x3E8EDE UMETA(DisplayName = "Tufts Blue"),
	Tumbleweed = 0xDEAA88 UMETA(DisplayName = "Tumbleweed"),
	Turquoise = 0x40E0D0 UMETA(DisplayName = "Turquoise"),
	Turquoise_Blue = 0x00FFEF UMETA(DisplayName = "Turquoise Blue"),
	Turquoise_Green = 0xA0D6B4 UMETA(DisplayName = "Turquoise Green"),
	Tuscan_Red = 0x7C4848 UMETA(DisplayName = "Tuscan Red"),
	Tuscany = 0xC09999 UMETA(DisplayName = "Tuscany"),
	Twilight_Lavender = 0x8A496B UMETA(DisplayName = "Twilight Lavender"),
	Tyrian_Purple = 0x66023C UMETA(DisplayName = "Tyrian Purple"),
	Ua_Blue = 0x0033AA UMETA(DisplayName = "Ua Blue"),
	Ua_Red = 0xD9004C UMETA(DisplayName = "Ua Red"),
	Ultra_Pink = 0xFF6FFF UMETA(DisplayName = "Ultra Pink"),
	Ultra_Red = 0xFC6C85 UMETA(DisplayName = "Ultra Red"),
	Ultramarine = 0x3F00FF UMETA(DisplayName = "Ultramarine"),
	Ultramarine_Blue = 0x4166F5 UMETA(DisplayName = "Ultramarine Blue"),
	Umber = 0x635147 UMETA(DisplayName = "Umber"),
	Unbleached_Silk = 0xFFDDCA UMETA(DisplayName = "Unbleached Silk"),
	United_Nations_Blue = 0x5B92E5 UMETA(DisplayName = "United Nations Blue"),
	University_Of_Pennsylvania_Red =
		0xA50021 UMETA(DisplayName = "University Of Pennsylvania Red"),
	Up_Maroon = 0x7B1113 UMETA(DisplayName = "Up Maroon"),
	Upsdell_Red = 0xAE2029 UMETA(DisplayName = "Upsdell Red"),
	Uranian_Blue = 0xAFDBF5 UMETA(DisplayName = "Uranian Blue"),
	Usafa_Blue = 0x004F98 UMETA(DisplayName = "Usafa Blue"),
	Van_Dyke_Brown = 0x664228 UMETA(DisplayName = "Van Dyke Brown"),
	Vanilla = 0xF3E5AB UMETA(DisplayName = "Vanilla"),
	Vanilla_Ice = 0xF38FA9 UMETA(DisplayName = "Vanilla Ice"),
	Vegas_Gold = 0xC5B358 UMETA(DisplayName = "Vegas Gold"),
	Venetian_Red = 0xC80815 UMETA(DisplayName = "Venetian Red"),
	Verdigris = 0x43B3AE UMETA(DisplayName = "Verdigris"),
	Vermilion = 0xE34234 UMETA(DisplayName = "Vermilion"),
	Veronica_Purple = 0xA020F0 UMETA(DisplayName = "Veronica Purple"),
	Violet = 0x8F00FF UMETA(DisplayName = "Violet"),
	Violet_Blue = 0x324AB2 UMETA(DisplayName = "Violet Blue"),
	Violet_Red = 0xF75394 UMETA(DisplayName = "Violet Red"),
	Violet_Ryb = 0x8601AF UMETA(DisplayName = "Violet Ryb"),
	Viridian = 0x40826D UMETA(DisplayName = "Viridian"),
	Viridian_Green = 0x009698 UMETA(DisplayName = "Viridian Green"),
	Vivid_Burgundy = 0x9F1D35 UMETA(DisplayName = "Vivid Burgundy"),
	Vivid_Sky_Blue = 0x00CCFF UMETA(DisplayName = "Vivid Sky Blue"),
	Vivid_Tangerine = 0xFFA089 UMETA(DisplayName = "Vivid Tangerine"),
	Vivid_Violet = 0x9F00FF UMETA(DisplayName = "Vivid Violet"),
	Volt = 0xCEFF00 UMETA(DisplayName = "Volt"),
	Warm_Black = 0x004242 UMETA(DisplayName = "Warm Black"),
	Web_Azure = 0xF0FFFF UMETA(DisplayName = "Web Azure"),
	Web_Chartreuse = 0x7FFF00 UMETA(DisplayName = "Web Chartreuse"),
	Web_Chocolate = 0xD2691E UMETA(DisplayName = "Web Chocolate"),
	Web_Forest_Green = 0x228B22 UMETA(DisplayName = "Web Forest Green"),
	Web_Gold_Golden = 0xFFD700 UMETA(DisplayName = "Web Gold Golden"),
	Web_Gray = 0x808080 UMETA(DisplayName = "Web Gray"),
	Web_Green = 0x008000 UMETA(DisplayName = "Web Green"),
	Web_Khaki = 0xC3B091 UMETA(DisplayName = "Web Khaki"),
	Web_Lavender = 0xE6E6FA UMETA(DisplayName = "Web Lavender"),
	Web_Maroon = 0x800000 UMETA(DisplayName = "Web Maroon"),
	Web_Orange = 0xFFA500 UMETA(DisplayName = "Web Orange"),
	Web_Plum = 0xDDA0DD UMETA(DisplayName = "Web Plum"),
	Web_Purple = 0x800080 UMETA(DisplayName = "Web Purple"),
	Web_Violet = 0xEE82EE UMETA(DisplayName = "Web Violet"),
	Weezy_Blue = 0x189BCC UMETA(DisplayName = "Weezy Blue"),
	Wheat = 0xF5DEB3 UMETA(DisplayName = "Wheat"),
	White = 0xFFFFFF UMETA(DisplayName = "White"),
	Wild_Blue_Yonder = 0xA2ADD0 UMETA(DisplayName = "Wild Blue Yonder"),
	Wild_Orchid = 0xD470A2 UMETA(DisplayName = "Wild Orchid"),
	Wild_Strawberry = 0xFF43A4 UMETA(DisplayName = "Wild Strawberry"),
	Windsor_Tan = 0xA75502 UMETA(DisplayName = "Windsor Tan"),
	Wine = 0x722F37 UMETA(DisplayName = "Wine"),
	Winter_Sky = 0xFF007C UMETA(DisplayName = "Winter Sky"),
	Wintergreen_Dream = 0x56887D UMETA(DisplayName = "Wintergreen Dream"),
	Wisteria = 0xC9A0DC UMETA(DisplayName = "Wisteria"),
	Wood_Brown = 0xC19A6B UMETA(DisplayName = "Wood Brown"),
	Xanadu = 0x738678 UMETA(DisplayName = "Xanadu"),
	Xanthic = 0xEEED09 UMETA(DisplayName = "Xanthic"),
	Xanthous = 0xF1B42F UMETA(DisplayName = "Xanthous"),
	Yale_Blue = 0x00356B UMETA(DisplayName = "Yale Blue"),
	Yellow = 0xFFFF00 UMETA(DisplayName = "Yellow"),
	Yellow_Green = 0x9ACD32 UMETA(DisplayName = "Yellow Green"),
	Yellow_Munsell = 0xEFCC00 UMETA(DisplayName = "Yellow Munsell"),
	Yellow_Orange = 0xFFAE42 UMETA(DisplayName = "Yellow Orange"),
	Yellow_Pantone = 0xFEDF00 UMETA(DisplayName = "Yellow Pantone"),
	Yellow_Ryb = 0xFEFE33 UMETA(DisplayName = "Yellow Ryb"),
	Yinmn_Blue = 0x2E5090 UMETA(DisplayName = "Yinmn Blue"),
	Zaffre = 0x0014A8 UMETA(DisplayName = "Zaffre"),
	Zomp = 0x39A78E UMETA(DisplayName = "Zomp"),
};

FORCEINLINE FLinearColor ToLinearColor(EPalette Palette)
{
	static_assert(sizeof(Palette) == sizeof(uint32));
	uint32 Bytes = static_cast<uint32>(Palette);
	return FLinearColor(
		FColor((Bytes >> 16) & 0xFF, (Bytes >> 8) & 0xFF, (Bytes >> 0) & 0xFF));
}
